name: FirstWorkflow
on : [push]
jobs:
  run-shell-command:
           runs-on: ubuntu-latest
           steps:
             - name: Echo a String
               run: echo "Hello World"
             - name: Python commands
               id: python_command
               run: |
                   import platform
                   print(platform.processor())
               shell: python
             - name: Output Steps
               run : echo "${{steps.python_command}}"
             - name: List Files
               run: |
                  pwd
                  ls 
             - name: Checkout
               uses: actions/checkout@v1
             - name: List Files after checkout
               run: |
                  pwd
                  ls -al
              

